markdown: rdiscount
highlighter: pygments
domain: 'https://datenschule.de'
staticurl: /assets/
baseurl: ""
exclude:
  - "CNAME"
  - "LICENSE"
  - "browserlist"
  - "Gemfile*"
  - "Readme.md"
  - "*.sh"
  - ".idea/"
  - ".git/"
  - "local/"
  - "scripts/"
  - "_site/"
  - "vendor/"
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  - octopress-autoprefixer
page_gen:
  - data: cards
    template: card
    name: id
    dir: card
    extension: html
languages: ["de", "en"]
languages_bak: ["de", "en"]
lang_report_missing: false
exclude_from_localizations: ["assets", "files", "style", "js", "svg", "fonts", "images", "scripts"]
timezone: Europe/Berlin
tag_dir: blog/tags/
permalink: blog/:year/:month/:title/
paginate: 8
paginate_path: blog/page/:num/
sass:
  sass_dir: assets/style/_scss
  style: compressed
defaults:
  - scope:
      path: "blog"
      type: "posts"
    values:
      layout: "post"
      card: true
  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: "tutorial"
      card: true
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "topics"
    values:
      layouts: "topic"
collections:
  tutorials:
    output: true
    permalink: /tutorial/:path/
  projects:
    output: true
    permalink: /projekte/:path/
  workshops:
    output: true
    permalink: /workshops/:path/
  testimonials:
    output: true
    permalink: /referenzen/:path/
  topics:
    output: true
    permalink: /lernen/themen/:path/
settings:
  debug: false
