- name: Helene Hahn
  img: helenehahn
  mail: helene.hahn@okfn.de
  job: Projektleitung OKF DE
  job_en: Project lead

- name: Knut Perseke
  img: knutperseke
  mail: knut.perseke@okfn.de
  job: Software-Entwicklung
  job_en: Developer

- name: Moritz Neujeffski
  img: moritzneujeffski
  mail: moritz.neujeffski@okfn.de
  job: Workshopkonzeption
  job_en: Workshop conception

- name: Jasmin Helm
  img: jasminhelm
  mail: jasmin.helm@okfn.de
  job: Kommunikation
  job_en: Communication
